services:
  - type: web
    name: wota-recognize
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 2 --timeout 300 -b 0.0.0.0:$PORT
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
